In [4]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests, re
import itertools as it
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select

from selenium.webdriver.support import expected_conditions as EC
import warnings
warnings.filterwarnings('ignore')
import random
import time
import math

In [5]:
base_url = 'https://www.crunchbase.com/discover/organization.companies/1df27c6c529133cb72a545b6656f7c40'
driver = webdriver.Chrome()
driver.get(base_url)

In [44]:
maxpage = driver.find_element_by_xpath('/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[1]/div/results-info/h3').text
maxp = int(maxpage.split('\n')[-1].split(' ')[1].replace(',',''))
page = math.ceil(maxp/50)
page

7

In [5]:
### Link

row = driver.find_elements_by_class_name('ng-star-inserted')[0]
lst = driver.find_elements_by_xpath('/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row')
link = driver.find_elements_by_link_text('View on LinkedIn')
link[0].get_attribute('href')
#'/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row[1]/grid-cell[5]/div'
#'/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row[3]/grid-cell[5]/div'

'https://www.linkedin.com/company/getdutchie/'

In [13]:
lst = driver.find_elements_by_xpath('/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row')
for i in lst:
    all_info = i.text
    company_name = all_info.split('\n')[1]
    location = all_info.split('\n')[2]

In [46]:
pg =1
companies = []
while pg <= page:
    lst = driver.find_elements_by_xpath('/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row')
    for i in lst:
        all_info = i.text
        company_name = all_info.split('\n')[1]
        location = all_info.split('\n')[2]
        try:
            Link = i.find_element_by_link_text('View on LinkedIn').get_attribute('href')
        except:
            Link = ''
        
        companies.append([company_name,Link,location,'AV/EV'])
    
    try:
        nxt = driver.find_element_by_link_text('NEXT')
        nxt.click()
        print('Page '+str(pg)+" Scraped")

        try:
            element_present = EC.presence_of_element_located((By.XPATH, '/html/body/chrome/div/mat-sidenav-container/mat-sidenav-content/div/discover/page-layout/div/div/div[2]/section[2]/results/div/div/div[3]/sheet-grid/div/div/grid-body/div/grid-row[50]'))
            WebDriverWait(driver, 20).until(element_present)
        except:
            print(str(pg)+' Last element not loaded')
            sleep(5)
        pg+=1
    except:
        print('finished')
        break
df = pd.DataFrame(companies,columns=['name','link','location','industry'])

Page 1 Scraped
Page 2 Scraped
Page 3 Scraped
Page 4 Scraped
Page 5 Scraped
Page 6 Scraped
finished

In [47]:
df

,name,link,location,industry
0,Seegrid,https://www.linkedin.com/company/seegrid/,"Pittsburgh, Pennsylvania, United States",AV/EV
1,AutoX,https://www.linkedin.com/company/18239945/,"San Jose, California, United States",AV/EV
2,Voyage,https://www.linkedin.com/company/18078448,"Palo Alto, California, United States",AV/EV
3,Workhorse Group,https://www.linkedin.com/company/workhorse-cus...,"Loveland, Ohio, United States",AV/EV
4,Affectiva,http://www.linkedin.com/company/722122,"Boston, Massachusetts, United States",AV/EV
...,...,...,...,...
345,Hero Motorsports,,"Van Nuys, California, United States",AV/EV
346,Macpela Towing,,"Newark, New Jersey, United States",AV/EV
347,Electric Cablempounds,https://www.linkedin.com/company/electric-cabl...,"Naugatuck, Connecticut, United States",AV/EV
348,Car cover guys,,"Las Vegas, Nevada, United States",AV/EV
349,Sharpell Technologies,https://www.linkedin.com/company/sharpell-tech...,"San Luis Obispo, California, United States",AV/EV

In [48]:
df.to_csv('AV-US.csv',index=False)

In [71]:
ec1 = pd.read_csv('E-commerce-west.csv')
ec2 = pd.read_csv('E-commerce-MW-South.csv')
ec3 = pd.read_csv('E-commerce-NE.csv')
df1 = pd.concat([ec1,ec2,ec3])
df1.columns=['name','link','location']
df1['industry'] = 'E-Commerce'
sm = pd.read_csv('Social-media-US.csv')
sm.columns=['name','link','location']
sm['industry'] = 'Social Media'
cl = pd.read_csv('Cloud-US.csv')
game = pd.read_csv('Entertainment-US.csv')
av = pd.read_csv('AV-US.csv')
df = pd.concat([df1,sm,cl,game,av])

In [78]:
df.to_csv('companies-9-17.csv',index=False)

In [79]:
df

,name,link,location,industry
0,Dutchie,https://www.linkedin.com/company/getdutchie/,"Bend, Oregon, United States",E-Commerce
1,Finix,https://www.linkedin.com/company/finix-payments/,"San Francisco, California, United States",E-Commerce
2,Hims,https://www.linkedin.com/company/hims-inc/,"San Francisco, California, United States",E-Commerce
3,Mayvenn,NaN,"Oakland, California, United States",E-Commerce
4,Octane AI,https://www.linkedin.com/company/octane-ai,"San Francisco, California, United States",E-Commerce
...,...,...,...,...
345,Hero Motorsports,NaN,"Van Nuys, California, United States",AV/EV
346,Macpela Towing,NaN,"Newark, New Jersey, United States",AV/EV
347,Electric Cablempounds,https://www.linkedin.com/company/electric-cabl...,"Naugatuck, Connecticut, United States",AV/EV
348,Car cover guys,NaN,"Las Vegas, Nevada, United States",AV/EV
349,Sharpell Technologies,https://www.linkedin.com/company/sharpell-tech...,"San Luis Obispo, California, United States",AV/EV

## LinkedIn

In [3]:
df_sum = []
index = 1
for i in df['LinkedIn']:
    try:
        driver.get(i+'/jobs/')
        element_click = EC.element_to_be_clickable((By.LINK_TEXT, 'Insights'))
        WebDriverWait(driver, 5).until(element_click)
        menu = driver.find_element_by_class_name('org-grid__left-rail')
        try:
            employees = driver.find_element_by_partial_link_text('See all').text
        except:
            employees =''

        try:
            element_present = EC.presence_of_element_located((By.CLASS_NAME, 'org-jobs-job-search-form-module__headline'))
            WebDriverWait(driver, 3).until(element_present)
            jobopenings = int(driver.find_element_by_class_name('org-jobs-job-search-form-module__headline').text.split('job')[0].strip().split(' ')[-1])
        except:
            jobopenings = ''

        try:
            menu.find_element_by_link_text('Insights').click()
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        except:
            print('No.'+str(index)+' Insights Page Not Clickable')
        #sleep(random.random()*10+3)
        try:
            element_present = EC.presence_of_all_elements_located((By.CSS_SELECTOR, 'td.org-insights-module__summary-block'))
            WebDriverWait(driver, 7).until(element_present)
            yr_sum = driver.find_elements_by_css_selector('td.org-insights-module__summary-block')
            hlfyr=yr_sum[1].text
            oneyr=yr_sum[2].text
            twoyr=yr_sum[3].text
        except:
            hlfyr=''
            oneyr=''
            twoyr=''
            print('No.'+str(index)+' Insights Page Missing Info')
        summary = [jobopenings,employees,hlfyr,oneyr,twoyr,i]
    except:
        summary = ['na','na','na','na','na',i]
        print(str(index)+' Link Not working')
    df_sum.append(summary)
    print(str(index)+ ' Finished')
    index+=1
df_final = pd.DataFrame(df_sum,columns=['job_openings','# employees','hlfyr','oneyr','twoyr','link'])
df_final

1 Finished
2 Finished
No.3 Insights Page Missing Info
3 Finished
4 Finished
5 Finished
No.6 Insights Page Missing Info
6 Finished
7 Finished
8 Finished
9 Finished
10 Finished
11 Finished
12 Finished
13 Finished
14 Finished
15 Finished
16 Finished
17 Finished
18 Finished
No.19 Insights Page Missing Info
19 Finished
20 Finished
21 Finished
22 Link Not working
22 Finished
No.23 Insights Page Missing Info
23 Finished
No.24 Insights Page Missing Info
24 Finished
No.25 Insights Page Missing Info
25 Finished
26 Finished
27 Link Not working
27 Finished
28 Finished
29 Finished
30 Finished
31 Finished
No.32 Insights Page Missing Info
32 Finished
No.33 Insights Page Missing Info
33 Finished
34 Finished
35 Finished
36 Finished
37 Finished
38 Finished
39 Finished
No.40 Insights Page Missing Info
40 Finished
No.41 Insights Page Missing Info
41 Finished
No.42 Insights Page Missing Info
42 Finished
No.43 Insights Page Missing Info
43 Finished
No.44 Insights Page Missing Info
44 Finished
45 Link Not working
45 Finished
46 Finished
47 Finished
No.48 Insights Page Missing Info
48 Finished
49 Finished
50 Finished
51 Finished
52 Finished
53 Finished
No.54 Insights Page Missing Info
54 Finished
No.55 Insights Page Missing Info
55 Finished
56 Finished
57 Finished
58 Finished
59 Finished
60 Finished
No.61 Insights Page Missing Info
61 Finished
62 Finished
63 Finished
64 Link Not working
64 Finished
65 Finished
66 Finished
67 Finished
No.68 Insights Page Missing Info
68 Finished
69 Finished
70 Finished
71 Finished
No.72 Insights Page Missing Info
72 Finished
73 Link Not working
73 Finished
74 Finished
75 Finished
76 Finished
77 Finished
78 Finished
79 Finished
80 Finished
No.81 Insights Page Missing Info
81 Finished
No.82 Insights Page Missing Info
82 Finished
No.83 Insights Page Missing Info
83 Finished
No.84 Insights Page Missing Info
84 Finished
No.85 Insights Page Missing Info
85 Finished
No.86 Insights Page Missing Info
86 Finished
No.87 Insights Page Missing Info
87 Finished
No.88 Insights Page Missing Info
88 Finished
No.89 Insights Page Missing Info
89 Finished
90 Finished
91 Finished
92 Finished
93 Finished
94 Finished
95 Finished
No.96 Insights Page Missing Info
96 Finished
No.97 Insights Page Missing Info
97 Finished
No.98 Insights Page Missing Info
98 Finished
99 Link Not working
99 Finished
No.100 Insights Page Missing Info
100 Finished
101 Finished
No.102 Insights Page Missing Info
102 Finished
103 Finished
No.104 Insights Page Missing Info
104 Finished
105 Finished
106 Finished
107 Finished
No.108 Insights Page Missing Info
108 Finished
No.109 Insights Page Missing Info
109 Finished
110 Finished
111 Finished
No.112 Insights Page Missing Info
112 Finished
No.113 Insights Page Missing Info
113 Finished
No.114 Insights Page Missing Info
114 Finished
115 Finished
116 Finished
No.117 Insights Page Missing Info
117 Finished
No.118 Insights Page Missing Info
118 Finished
119 Finished
No.120 Insights Page Missing Info
120 Finished
121 Finished
122 Finished
123 Link Not working
123 Finished
124 Finished
No.125 Insights Page Missing Info
125 Finished
126 Finished
No.127 Insights Page Missing Info
127 Finished
128 Finished
129 Finished
130 Finished
131 Finished
132 Finished
No.133 Insights Page Missing Info
133 Finished
134 Finished
135 Finished
136 Finished
No.137 Insights Page Missing Info
137 Finished
No.138 Insights Page Missing Info
138 Finished
139 Finished
No.140 Insights Page Missing Info
140 Finished
141 Finished
142 Finished
No.143 Insights Page Missing Info
143 Finished
No.144 Insights Page Missing Info
144 Finished
No.145 Insights Page Missing Info
145 Finished
No.146 Insights Page Missing Info
146 Finished
No.147 Insights Page Missing Info
147 Finished
No.148 Insights Page Missing Info
148 Finished
149 Finished
150 Finished
151 Finished
No.152 Insights Page Missing Info
152 Finished
153 Link Not working
153 Finished
154 Finished
155 Finished
No.156 Insights Page Missing Info
156 Finished
No.157 Insights Page Missing Info
157 Finished
No.158 Insights Page Missing Info
158 Finished
159 Finished
160 Finished
No.161 Insights Page Missing Info
161 Finished
No.162 Insights Page Missing Info
162 Finished
163 Link Not working
163 Finished
164 Finished
No.165 Insights Page Missing Info
165 Finished
No.166 Insights Page Missing Info
166 Finished
No.167 Insights Page Missing Info
167 Finished
No.168 Insights Page Missing Info
168 Finished
No.169 Insights Page Missing Info
169 Finished
No.170 Insights Page Missing Info
170 Finished
171 Finished
No.172 Insights Page Missing Info
172 Finished
No.173 Insights Page Missing Info
173 Finished
No.174 Insights Page Missing Info
174 Finished
175 Finished
No.176 Insights Page Missing Info
176 Finished
177 Link Not working
177 Finished
178 Link Not working
178 Finished
No.179 Insights Page Missing Info
179 Finished
No.180 Insights Page Missing Info
180 Finished
181 Finished
182 Finished
No.183 Insights Page Missing Info
183 Finished
No.184 Insights Page Missing Info
184 Finished
No.185 Insights Page Missing Info
185 Finished
No.186 Insights Page Missing Info
186 Finished
187 Finished
188 Finished
189 Finished
No.190 Insights Page Missing Info
190 Finished
191 Finished
No.192 Insights Page Missing Info
192 Finished
193 Finished
No.194 Insights Page Missing Info
194 Finished
No.195 Insights Page Missing Info
195 Finished
196 Finished
197 Link Not working
197 Finished
No.198 Insights Page Missing Info
198 Finished
199 Finished
No.200 Insights Page Missing Info
200 Finished
No.201 Insights Page Missing Info
201 Finished
No.202 Insights Page Missing Info
202 Finished
No.203 Insights Page Missing Info
203 Finished
No.204 Insights Page Missing Info
204 Finished
205 Finished
206 Finished
207 Finished
No.208 Insights Page Missing Info
208 Finished
No.209 Insights Page Missing Info
209 Finished
210 Finished
No.211 Insights Page Missing Info
211 Finished
212 Finished
No.213 Insights Page Missing Info
213 Finished
No.214 Insights Page Missing Info
214 Finished
No.215 Insights Page Missing Info
215 Finished
216 Finished
217 Link Not working
217 Finished
No.218 Insights Page Missing Info
218 Finished
No.219 Insights Page Missing Info
219 Finished
No.220 Insights Page Missing Info
220 Finished
No.221 Insights Page Missing Info
221 Finished
No.222 Insights Page Missing Info
222 Finished
223 Finished
224 Link Not working
224 Finished
225 Link Not working
225 Finished
No.226 Insights Page Missing Info
226 Finished
227 Finished
228 Finished
No.229 Insights Page Missing Info
229 Finished
230 Finished
No.231 Insights Page Missing Info
231 Finished
232 Finished
No.233 Insights Page Missing Info
233 Finished
No.234 Insights Page Missing Info
234 Finished
235 Finished
236 Finished
237 Link Not working
237 Finished
238 Link Not working
238 Finished
No.239 Insights Page Missing Info
239 Finished
240 Finished
241 Finished
No.242 Insights Page Missing Info
242 Finished
No.243 Insights Page Missing Info
243 Finished
244 Link Not working
244 Finished
No.245 Insights Page Missing Info
245 Finished
246 Finished
No.247 Insights Page Missing Info
247 Finished
No.248 Insights Page Missing Info
248 Finished
No.249 Insights Page Missing Info
249 Finished
250 Finished
251 Finished
252 Link Not working
252 Finished
No.253 Insights Page Missing Info
253 Finished
No.254 Insights Page Missing Info
254 Finished
No.255 Insights Page Missing Info
255 Finished
No.256 Insights Page Missing Info
256 Finished
No.257 Insights Page Missing Info
257 Finished
258 Finished
No.259 Insights Page Missing Info
259 Finished
No.260 Insights Page Missing Info
260 Finished
261 Finished
262 Link Not working
262 Finished
No.263 Insights Page Missing Info
263 Finished
264 Link Not working
264 Finished
No.265 Insights Page Missing Info
265 Finished
No.266 Insights Page Missing Info
266 Finished
No.267 Insights Page Missing Info
267 Finished
No.268 Insights Page Missing Info
268 Finished
No.269 Insights Page Missing Info
269 Finished
270 Finished
No.271 Insights Page Missing Info
271 Finished
No.272 Insights Page Missing Info
272 Finished
No.273 Insights Page Missing Info
273 Finished
274 Finished
No.275 Insights Page Missing Info
275 Finished
No.276 Insights Page Missing Info
276 Finished

No.277 Insights Page Missing Info
277 Finished
278 Finished
279 Finished
280 Link Not working
280 Finished
281 Link Not working
281 Finished
282 Link Not working
282 Finished
283 Link Not working
283 Finished
No.284 Insights Page Missing Info
284 Finished
285 Finished
No.286 Insights Page Missing Info
286 Finished
287 Finished
288 Finished
289 Link Not working
289 Finished
290 Link Not working
290 Finished
291 Link Not working
291 Finished
292 Finished
No.293 Insights Page Missing Info
293 Finished
294 Finished
No.295 Insights Page Missing Info
295 Finished
296 Finished
297 Link Not working
297 Finished
No.298 Insights Page Missing Info
298 Finished
299 Finished
300 Finished
301 Finished
No.302 Insights Page Missing Info
302 Finished
No.303 Insights Page Missing Info
303 Finished
No.304 Insights Page Missing Info
304 Finished
No.305 Insights Page Missing Info
305 Finished
No.306 Insights Page Missing Info
306 Finished
No.307 Insights Page Missing Info
307 Finished
No.308 Insights Page Missing Info
308 Finished
No.309 Insights Page Missing Info
309 Finished
No.310 Insights Page Missing Info
310 Finished
311 Finished
312 Link Not working
312 Finished
No.313 Insights Page Missing Info
313 Finished
No.314 Insights Page Missing Info
314 Finished
No.315 Insights Page Missing Info
315 Finished
No.316 Insights Page Missing Info
316 Finished
No.317 Insights Page Missing Info
317 Finished
318 Finished
No.319 Insights Page Missing Info
319 Finished
320 Finished
No.321 Insights Page Missing Info
321 Finished
No.322 Insights Page Missing Info
322 Finished
No.323 Insights Page Missing Info
323 Finished
No.324 Insights Page Missing Info
324 Finished
325 Finished
326 Link Not working
326 Finished
No.327 Insights Page Missing Info
327 Finished
No.328 Insights Page Missing Info
328 Finished
No.329 Insights Page Missing Info
329 Finished
330 Finished
No.331 Insights Page Missing Info
331 Finished
No.332 Insights Page Missing Info
332 Finished
No.333 Insights Page Missing Info
333 Finished
334 Finished
335 Finished
336 Finished
337 Finished
338 Finished
339 Finished
340 Finished
341 Finished
342 Finished
343 Finished
344 Finished
345 Link Not working
345 Finished
346 Finished
347 Link Not working
347 Finished
348 Finished
No.349 Insights Page Missing Info
349 Finished
350 Finished
351 Finished
352 Finished
353 Finished
354 Finished
355 Finished
356 Finished
357 Finished
358 Finished
No.359 Insights Page Missing Info
359 Finished
360 Finished
361 Finished
362 Finished
363 Link Not working
363 Finished
No.364 Insights Page Missing Info
364 Finished
No.365 Insights Page Missing Info
365 Finished
366 Link Not working
366 Finished
No.367 Insights Page Missing Info
367 Finished
No.368 Insights Page Missing Info
368 Finished
No.369 Insights Page Missing Info
369 Finished
370 Finished
371 Finished
372 Finished
No.373 Insights Page Missing Info
373 Finished
No.374 Insights Page Missing Info
374 Finished
375 Finished
No.376 Insights Page Missing Info
376 Finished
No.377 Insights Page Missing Info
377 Finished
No.378 Insights Page Missing Info
378 Finished
379 Finished
380 Finished
381 Finished
No.382 Insights Page Missing Info
382 Finished
383 Finished
384 Finished
385 Finished
386 Finished
387 Finished
388 Finished
No.389 Insights Page Missing Info
389 Finished
390 Finished
391 Link Not working
391 Finished
392 Link Not working
392 Finished
393 Finished
394 Finished
395 Finished
396 Finished
397 Finished
398 Finished
No.399 Insights Page Missing Info
399 Finished
400 Finished
401 Finished
402 Finished
403 Link Not working
403 Finished
404 Link Not working
404 Finished
405 Finished
406 Finished
407 Finished
408 Finished
409 Finished
410 Finished
411 Finished
No.412 Insights Page Missing Info
412 Finished
413 Finished
414 Finished
415 Finished
416 Finished
417 Finished
418 Link Not working
418 Finished
419 Finished
420 Finished
No.421 Insights Page Missing Info
421 Finished
422 Finished
423 Finished
424 Finished
425 Finished
426 Finished
No.427 Insights Page Missing Info
427 Finished
No.428 Insights Page Missing Info
428 Finished
No.429 Insights Page Missing Info
429 Finished
430 Finished
No.431 Insights Page Missing Info
431 Finished
432 Link Not working
432 Finished
433 Finished
434 Finished
435 Finished
436 Finished
No.437 Insights Page Missing Info
437 Finished
No.438 Insights Page Missing Info
438 Finished
439 Finished
No.440 Insights Page Missing Info
440 Finished
441 Finished
442 Link Not working
442 Finished
443 Finished
No.444 Insights Page Missing Info
444 Finished
445 Finished
No.446 Insights Page Missing Info
446 Finished
No.447 Insights Page Missing Info
447 Finished
448 Link Not working
448 Finished
No.449 Insights Page Missing Info
449 Finished
450 Link Not working
450 Finished
No.451 Insights Page Missing Info
451 Finished
452 Finished
No.453 Insights Page Missing Info
453 Finished
No.454 Insights Page Missing Info
454 Finished
455 Finished
456 Link Not working
456 Finished
No.457 Insights Page Missing Info
457 Finished
458 Link Not working
458 Finished
459 Finished
No.460 Insights Page Missing Info
460 Finished
461 Finished
No.462 Insights Page Missing Info
462 Finished
No.463 Insights Page Missing Info
463 Finished
464 Finished
465 Link Not working
465 Finished
No.466 Insights Page Missing Info
466 Finished
No.467 Insights Page Missing Info
467 Finished
No.468 Insights Page Missing Info
468 Finished
469 Finished
No.470 Insights Page Missing Info
470 Finished
No.471 Insights Page Missing Info
471 Finished
No.472 Insights Page Missing Info
472 Finished
473 Finished
474 Link Not working
474 Finished
475 Finished
476 Finished
477 Link Not working
477 Finished
478 Finished
479 Link Not working
479 Finished
No.480 Insights Page Missing Info
480 Finished
481 Finished
482 Link Not working
482 Finished
No.483 Insights Page Missing Info
483 Finished
484 Link Not working
484 Finished
No.485 Insights Page Missing Info
485 Finished
No.486 Insights Page Missing Info
486 Finished
No.487 Insights Page Missing Info
487 Finished
488 Link Not working
488 Finished
No.489 Insights Page Missing Info
489 Finished
No.490 Insights Page Missing Info
490 Finished
491 Link Not working
491 Finished
492 Finished
No.493 Insights Page Missing Info
493 Finished
No.494 Insights Page Missing Info
494 Finished
No.495 Insights Page Missing Info
495 Finished
No.496 Insights Page Missing Info
496 Finished
No.497 Insights Page Missing Info
497 Finished
No.498 Insights Page Missing Info
498 Finished
499 Finished
No.500 Insights Page Missing Info
500 Finished
No.501 Insights Page Missing Info
501 Finished
No.502 Insights Page Missing Info
502 Finished
503 Link Not working
503 Finished
No.504 Insights Page Missing Info
504 Finished
505 Link Not working
505 Finished
No.506 Insights Page Missing Info
506 Finished
No.507 Insights Page Missing Info
507 Finished
508 Finished
No.509 Insights Page Missing Info
509 Finished
No.510 Insights Page Missing Info
510 Finished
511 Link Not working
511 Finished
No.512 Insights Page Missing Info
512 Finished
513 Link Not working
513 Finished
No.514 Insights Page Missing Info
514 Finished
No.515 Insights Page Missing Info
515 Finished
516 Finished
No.517 Insights Page Missing Info
517 Finished
No.518 Insights Page Missing Info
518 Finished
No.519 Insights Page Missing Info
519 Finished
No.520 Insights Page Missing Info
520 Finished
No.521 Insights Page Missing Info
521 Finished
No.522 Insights Page Missing Info
522 Finished
523 Link Not working
523 Finished
524 Link Not working
524 Finished
No.525 Insights Page Missing Info
525 Finished
No.526 Insights Page Missing Info
526 Finished
No.527 Insights Page Missing Info
527 Finished
528 Link Not working
528 Finished
529 Link Not working
529 Finished
530 Link Not working
530 Finished
No.531 Insights Page Missing Info
531 Finished
532 Finished
No.533 Insights Page Missing Info
533 Finished
No.534 Insights Page Missing Info
534 Finished
No.535 Insights Page Missing Info
535 Finished
536 Link Not working
536 Finished
537 Link Not working
537 Finished
No.538 Insights Page Missing Info
538 Finished
No.539 Insights Page Missing Info
539 Finished
540 Link Not working
540 Finished
No.541 Insights Page Missing Info
541 Finished

542 Finished
543 Finished
544 Finished
No.545 Insights Page Missing Info
545 Finished
546 Finished
547 Finished
548 Finished
549 Finished
550 Finished
551 Finished
552 Finished
553 Finished
554 Finished
555 Finished
556 Finished
No.557 Insights Page Missing Info
557 Finished
558 Finished
559 Link Not working
559 Finished
560 Finished
561 Link Not working
561 Finished
562 Finished
563 Finished
564 Finished
565 Finished
No.566 Insights Page Missing Info
566 Finished
No.567 Insights Page Missing Info
567 Finished
568 Finished
569 Finished
No.570 Insights Page Missing Info
570 Finished
No.571 Insights Page Missing Info
571 Finished
No.572 Insights Page Missing Info
572 Finished
No.573 Insights Page Missing Info
573 Finished
No.574 Insights Page Missing Info
574 Finished
No.575 Insights Page Missing Info
575 Finished
576 Finished
577 Finished
No.578 Insights Page Missing Info
578 Finished
579 Finished
580 Finished
581 Finished
582 Finished
583 Finished
No.584 Insights Page Missing Info
584 Finished
585 Finished
586 Finished
587 Finished
No.588 Insights Page Missing Info
588 Finished
589 Finished
590 Finished
591 Link Not working
591 Finished
592 Finished
593 Finished
594 Finished
595 Finished
596 Finished
597 Finished
No.598 Insights Page Missing Info
598 Finished
No.599 Insights Page Missing Info
599 Finished
600 Finished
601 Finished
602 Finished
No.603 Insights Page Missing Info
603 Finished
604 Finished
605 Finished
No.606 Insights Page Missing Info
606 Finished
607 Finished
608 Finished
609 Finished
610 Finished
611 Finished
612 Finished
613 Finished
614 Finished
615 Finished
No.616 Insights Page Missing Info
616 Finished
617 Finished
No.618 Insights Page Missing Info
618 Finished
No.619 Insights Page Missing Info
619 Finished
620 Link Not working
620 Finished
621 Finished
622 Finished
623 Finished
624 Finished
No.625 Insights Page Missing Info
625 Finished
626 Link Not working
626 Finished
No.627 Insights Page Missing Info
627 Finished
628 Finished
629 Finished
630 Finished
No.631 Insights Page Missing Info
631 Finished
632 Finished
633 Finished
No.634 Insights Page Missing Info
634 Finished
635 Finished
636 Finished
No.637 Insights Page Missing Info
637 Finished
638 Finished
639 Finished
640 Finished
641 Finished
No.642 Insights Page Missing Info
642 Finished
643 Finished
644 Finished
No.645 Insights Page Missing Info
645 Finished
646 Finished
No.647 Insights Page Missing Info
647 Finished
648 Finished
No.649 Insights Page Missing Info
649 Finished
No.650 Insights Page Missing Info
650 Finished
651 Finished
652 Finished
653 Link Not working
653 Finished
No.654 Insights Page Missing Info
654 Finished
655 Finished
656 Finished
No.657 Insights Page Missing Info
657 Finished
No.658 Insights Page Missing Info
658 Finished
659 Finished
No.660 Insights Page Missing Info
660 Finished
No.661 Insights Page Missing Info
661 Finished
No.662 Insights Page Missing Info
662 Finished
663 Finished
No.664 Insights Page Missing Info
664 Finished
665 Finished
666 Finished
667 Finished
668 Finished
No.669 Insights Page Missing Info
669 Finished
670 Finished
671 Link Not working
671 Finished
672 Finished
No.673 Insights Page Missing Info
673 Finished
674 Link Not working
674 Finished
No.675 Insights Page Missing Info
675 Finished
676 Link Not working
676 Finished
677 Finished
678 Finished
679 Finished
680 Link Not working
680 Finished
No.681 Insights Page Missing Info
681 Finished
No.682 Insights Page Missing Info
682 Finished
No.683 Insights Page Missing Info
683 Finished
684 Link Not working
684 Finished
685 Link Not working
685 Finished
No.686 Insights Page Missing Info
686 Finished
687 Finished
688 Finished
No.689 Insights Page Missing Info
689 Finished
No.690 Insights Page Missing Info
690 Finished
No.691 Insights Page Missing Info
691 Finished
No.692 Insights Page Missing Info
692 Finished
No.693 Insights Page Missing Info
693 Finished
No.694 Insights Page Missing Info
694 Finished
No.695 Insights Page Missing Info
695 Finished
No.696 Insights Page Missing Info
696 Finished
No.697 Insights Page Missing Info
697 Finished
No.698 Insights Page Missing Info
698 Finished
699 Finished
700 Finished
701 Link Not working
701 Finished
No.702 Insights Page Missing Info
702 Finished
703 Finished
704 Link Not working
704 Finished
705 Finished
No.706 Insights Page Missing Info
706 Finished
No.707 Insights Page Missing Info
707 Finished
708 Finished
No.709 Insights Page Missing Info
709 Finished
710 Finished
No.711 Insights Page Missing Info
711 Finished
No.712 Insights Page Missing Info
712 Finished
713 Link Not working
713 Finished
No.714 Insights Page Missing Info
714 Finished
No.715 Insights Page Missing Info
715 Finished
No.716 Insights Page Missing Info
716 Finished
No.717 Insights Page Missing Info
717 Finished
No.718 Insights Page Missing Info
718 Finished
719 Finished
No.720 Insights Page Missing Info
720 Finished
721 Finished
No.722 Insights Page Missing Info
722 Finished
No.723 Insights Page Missing Info
723 Finished
724 Finished
No.725 Insights Page Missing Info
725 Finished
No.726 Insights Page Missing Info
726 Finished
No.727 Insights Page Missing Info
727 Finished
728 Link Not working
728 Finished
729 Link Not working
729 Finished
No.730 Insights Page Missing Info
730 Finished
No.731 Insights Page Missing Info
731 Finished
No.732 Insights Page Missing Info
732 Finished
733 Link Not working
733 Finished
734 Finished
No.735 Insights Page Missing Info
735 Finished
No.736 Insights Page Missing Info
736 Finished
No.737 Insights Page Missing Info
737 Finished
No.738 Insights Page Missing Info
738 Finished
No.739 Insights Page Missing Info
739 Finished
No.740 Insights Page Missing Info
740 Finished
No.741 Insights Page Missing Info
741 Finished
No.742 Insights Page Missing Info
742 Finished
743 Link Not working
743 Finished
744 Finished
No.745 Insights Page Missing Info
745 Finished
No.746 Insights Page Missing Info
746 Finished
747 Link Not working
747 Finished
748 Link Not working
748 Finished
No.749 Insights Page Missing Info
749 Finished
750 Finished
751 Finished
752 Link Not working
752 Finished
No.753 Insights Page Missing Info
753 Finished
No.754 Insights Page Missing Info
754 Finished
No.755 Insights Page Missing Info
755 Finished
No.756 Insights Page Missing Info
756 Finished
No.757 Insights Page Missing Info
757 Finished
No.758 Insights Page Missing Info
758 Finished
759 Link Not working
759 Finished
760 Link Not working
760 Finished
No.761 Insights Page Missing Info
761 Finished
762 Finished
763 Finished
No.764 Insights Page Missing Info
764 Finished
765 Finished
No.766 Insights Page Missing Info
766 Finished
767 Finished
768 Link Not working
768 Finished
No.769 Insights Page Missing Info
769 Finished
No.770 Insights Page Missing Info
770 Finished
No.771 Insights Page Missing Info
771 Finished
No.772 Insights Page Missing Info
772 Finished
773 Finished
774 Link Not working
774 Finished
775 Finished
No.776 Insights Page Missing Info
776 Finished
No.777 Insights Page Missing Info
777 Finished
778 Finished
779 Link Not working
779 Finished
No.780 Insights Page Missing Info
780 Finished
781 Link Not working
781 Finished
782 Link Not working
782 Finished
783 Link Not working
783 Finished
No.784 Insights Page Missing Info
784 Finished
No.785 Insights Page Missing Info
785 Finished
786 Finished
No.787 Insights Page Missing Info
787 Finished
No.788 Insights Page Missing Info
788 Finished
No.789 Insights Page Missing Info
789 Finished
No.790 Insights Page Missing Info
790 Finished
791 Link Not working
791 Finished
792 Link Not working
792 Finished
No.793 Insights Page Missing Info
793 Finished
No.794 Insights Page Missing Info
794 Finished
795 Finished
No.796 Insights Page Missing Info
796 Finished
No.797 Insights Page Missing Info
797 Finished
798 Finished
No.799 Insights Page Missing Info
799 Finished
800 Finished
No.801 Insights Page Missing Info
801 Finished
802 Link Not working
802 Finished
803 Link Not working
803 Finished
No.804 Insights Page Missing Info
804 Finished
No.805 Insights Page Missing Info
805 Finished
No.806 Insights Page Missing Info
806 Finished
No.807 Insights Page Missing Info
807 Finished
No.808 Insights Page Missing Info
808 Finished

No.809 Insights Page Missing Info
809 Finished
810 Link Not working
810 Finished
No.811 Insights Page Missing Info
811 Finished
No.812 Insights Page Missing Info
812 Finished
No.813 Insights Page Missing Info
813 Finished
No.814 Insights Page Missing Info
814 Finished
No.815 Insights Page Missing Info
815 Finished
816 Finished
No.817 Insights Page Missing Info
817 Finished
No.818 Insights Page Missing Info
818 Finished
No.819 Insights Page Missing Info
819 Finished
No.820 Insights Page Missing Info
820 Finished
821 Link Not working
821 Finished

,job_openings,# employees,hlfyr,oneyr,twoyr,link
0,7,See all 90 employees on LinkedIn,17%\n17% increase,105%\n105% increase,429%\n429% increase,https://www.linkedin.com/company/finix-payments/
1,,See all 89 employees on LinkedIn,1%\n1% increase,3%\n-3% decrease,10%\n10% increase,http://www.linkedin.com/company/4997584
2,,See all 26 employees on LinkedIn,,,,https://www.linkedin.com/company/beauty-bakeri...
3,15,See all 49 employees on LinkedIn,20%\n20% increase,29%\n29% increase,58%\n58% increase,https://www.linkedin.com/company/goldbelly/
4,3,See all 107 employees on LinkedIn,5%\n5% increase,9%\n9% increase,2%\n-2% decrease,https://www.linkedin.com/company/tophatter-com
...,...,...,...,...,...,...
816,,,,,,https://www.linkedin.com/company/skytide-inc
817,,See all 11 employees on LinkedIn,,,,https://www.linkedin.com/company/accordent-tec...
818,,,,,,https://www.linkedin.com/company/white-label-m...
819,,,,,,http://www.linkedin.com/company/gizmorati
820,na,na,na,na,na,https://www.linkedin.com/in/thibaultvignes

In [4]:
df_final

,job_openings,# employees,hlfyr,oneyr,twoyr,link
0,7,See all 90 employees on LinkedIn,17%\n17% increase,105%\n105% increase,429%\n429% increase,https://www.linkedin.com/company/finix-payments/
1,,See all 89 employees on LinkedIn,1%\n1% increase,3%\n-3% decrease,10%\n10% increase,http://www.linkedin.com/company/4997584
2,,See all 26 employees on LinkedIn,,,,https://www.linkedin.com/company/beauty-bakeri...
3,15,See all 49 employees on LinkedIn,20%\n20% increase,29%\n29% increase,58%\n58% increase,https://www.linkedin.com/company/goldbelly/
4,3,See all 107 employees on LinkedIn,5%\n5% increase,9%\n9% increase,2%\n-2% decrease,https://www.linkedin.com/company/tophatter-com
...,...,...,...,...,...,...
816,,,,,,https://www.linkedin.com/company/skytide-inc
817,,See all 11 employees on LinkedIn,,,,https://www.linkedin.com/company/accordent-tec...
818,,,,,,https://www.linkedin.com/company/white-label-m...
819,,,,,,http://www.linkedin.com/company/gizmorati
820,na,na,na,na,na,https://www.linkedin.com/in/thibaultvignes

In [46]:
number_lst = []
for i in df_final['# employees']:
    try:
        number = int(i.split(' ')[2].replace(',',''))
    except:
        number = 0
    number_lst.append(number)
df_final['headcount']=number_lst

In [93]:
df_missing = df_final[(df_final['headcount']>=30)&(df_final['twoyr']=='')]

In [61]:
df_final[(df_final['hlfyr']!='')&(df_final['hlfyr']!='na')]
df_final[df_final['job_openings']=='na']

,job_openings,# employees,hlfyr,oneyr,twoyr,link,headcount
21,na,na,na,na,na,https://www.linkedin.com/company/hi-burrow/,0
26,na,na,na,na,na,http://www.linkedin.com/company/stitch-labs-inc-,0
44,na,na,na,na,na,https://www.linkedin.com/company/full-harvest-...,0
63,na,na,na,na,na,https://www.linkedin.com/company-beta/10838707/,0
72,na,na,na,na,na,https://www.linkedin.com/in/luisana-mendoza-de...,0
...,...,...,...,...,...,...,...
791,na,na,na,na,na,https://www.linkedin.com/in/mfergason,0
801,na,na,na,na,na,https://www.linkedin.com/company/goodreads.com,0
802,na,na,na,na,na,http://www.linkedin.com/company/thewrap.com,0
809,na,na,na,na,na,https://www.linkedin.com/company-beta/2751012/,0
820,na,na,na,na,na,https://www.linkedin.com/in/thibaultvignes,0

In [69]:
df_final.to_csv('LinkedIn_1.csv',index=False)

## Fixings

In [77]:
driver = webdriver.Chrome()
driver.get(df_missing['link'][5])

In [99]:
new_links=[]
for i in df_missing['link']:
    if '/admin' in i:
        new_link=i.replace('admin/','insights/')
    else:    
        if i[-1] =='/':
            new_link = i+'insights'
        else:
            new_link = i+'/insights'
    new_links.append(new_link)

In [100]:
df_missing['insight_link'] = new_links
df_missing

,job_openings,# employees,hlfyr,oneyr,twoyr,link,headcount,insight_link
5,77,See all 484 employees on LinkedIn,20%\n20% increase,52%\n52% increase,,http://www.linkedin.com/company/klaviyo,484,http://www.linkedin.com/company/klaviyo/insights
22,11,See all 30 employees on LinkedIn,43%\n43% increase,67%\n67% increase,,https://www.linkedin.com/company/intego-co/,30,https://www.linkedin.com/company/intego-co/ins...
23,44,See all 243 employees on LinkedIn,9%\n9% increase,36%\n36% increase,,https://www.linkedin.com/company/homie-com,243,https://www.linkedin.com/company/homie-com/ins...
24,31,See all 155 employees on LinkedIn,13%\n13% increase,49%\n49% increase,,https://www.linkedin.com/company/shogun,155,https://www.linkedin.com/company/shogun/insights
31,,See all 82 employees on LinkedIn,9%\n9% increase,26%\n26% increase,,https://www.linkedin.com/company/flow.io,82,https://www.linkedin.com/company/flow.io/insights
32,16,See all 303 employees on LinkedIn,4%\n-4% decrease,4%\n-4% decrease,,https://www.linkedin.com/company/reformation,303,https://www.linkedin.com/company/reformation/i...
39,,See all 67 employees on LinkedIn,56%\n56% increase,97%\n97% increase,,https://www.linkedin.com/company/knowde/,67,https://www.linkedin.com/company/knowde/insights
40,4,See all 140 employees on LinkedIn,5%\n5% increase,7%\n7% increase,,https://www.linkedin.com/company/roadster,140,https://www.linkedin.com/company/roadster/insi...
41,4,See all 98 employees on LinkedIn,10%\n10% increase,13%\n13% increase,,https://www.linkedin.com/company/cotopaxi-com/,98,https://www.linkedin.com/company/cotopaxi-com/...
42,11,See all 51 employees on LinkedIn,34%\n34% increase,143%\n143% increase,,https://www.linkedin.com/company/bloomscape/,51,https://www.linkedin.com/company/bloomscape/in...
43,47,See all 120 employees on LinkedIn,20%\n20% increase,76%\n76% increase,,https://www.linkedin.com/company/curated-com/,120,https://www.linkedin.com/company/curated-com/i...
47,19,See all 78 employees on LinkedIn,,,,https://www.linkedin.com/company/hiextend/,78,https://www.linkedin.com/company/hiextend/insi...
71,9,See all 39 employees on LinkedIn,2%\n-2% decrease,15%\n15% increase,,https://www.linkedin.com/company/gosummersalt/,39,https://www.linkedin.com/company/gosummersalt/...
81,,See all 30 employees on LinkedIn,,,,https://www.linkedin.com/company/30683905/admin/,30,https://www.linkedin.com/company/30683905/insi...
82,1,See all 55 employees on LinkedIn,5%\n-5% decrease,12%\n12% increase,,https://www.linkedin.com/company/olivela/,55,https://www.linkedin.com/company/olivela/insights
83,18,See all 128 employees on LinkedIn,3%\n3% increase,1%\n1% increase,,https://www.linkedin.com/company/touchofmodern,128,https://www.linkedin.com/company/touchofmodern...
85,,See all 55 employees on LinkedIn,7%\n-7% decrease,5%\n-5% decrease,,https://www.linkedin.com/company/territoryfoods/,55,https://www.linkedin.com/company/territoryfood...
86,11,See all 73 employees on LinkedIn,4%\n4% increase,11%\n11% increase,,https://www.linkedin.com/company/webscalenetworks,73,https://www.linkedin.com/company/webscalenetwo...
87,,See all 157 employees on LinkedIn,6%\n6% increase,5%\n5% increase,,http://www.linkedin.com/company/inbenta,157,http://www.linkedin.com/company/inbenta/insights
88,4,See all 91 employees on LinkedIn,42%\n42% increase,60%\n60% increase,,https://www.linkedin.com/company/snappy-app/,91,https://www.linkedin.com/company/snappy-app/in...
95,,See all 34 employees on LinkedIn,0%\nNo change,31%\n-31% decrease,,https://www.linkedin.com/company/kidbox-usa/,34,https://www.linkedin.com/company/kidbox-usa/in...
96,4,See all 46 employees on LinkedIn,15%\n15% increase,35%\n35% increase,,https://www.linkedin.com/company/jane-technolo...,46,https://www.linkedin.com/company/jane-technolo...
97,,See all 34 employees on LinkedIn,6%\n6% increase,28%\n-28% decrease,,http://www.linkedin.com/company/skubana,34,http://www.linkedin.com/company/skubana/insights
99,2,See all 44 employees on LinkedIn,2%\n2% increase,6%\n-6% decrease,,http://www.linkedin.com/company/mytime,44,http://www.linkedin.com/company/mytime/insights
116,5,See all 74 employees on LinkedIn,7%\n7% increase,17%\n17% increase,,http://www.linkedin.com/company/2757474,74,http://www.linkedin.com/company/2757474/insights
157,,See all 40 employees on LinkedIn,,,,https://www.linkedin.com/company/higg-co,40,https://www.linkedin.com/company/higg-co/insights
411,24,See all 68 employees on LinkedIn,,,,https://www.linkedin.com/company/aresnalbio/,68,https://www.linkedin.com/company/aresnalbio/in...
571,2,See all 52 employees on LinkedIn,9%\n-9% decrease,13%\n-13% decrease,,https://www.linkedin.com/company/3103810/,52,https://www.linkedin.com/company/3103810/insights
572,,See all 59 employees on LinkedIn,3%\n-3% decrease,8%\n-8% decrease,,https://www.linkedin.com/company/13192804/,59,https://www.linkedin.com/company/13192804/insi...
573,5,See all 39 employees on LinkedIn,0%\nNo change,15%\n15% increase,,https://www.linkedin.com/company/phantomauto/,39,https://www.linkedin.com/company/phantomauto/i...
587,3,See all 38 employees on LinkedIn,,,,https://www.linkedin.com/company/recount-media,38,https://www.linkedin.com/company/recount-media...
783,,See all 30 employees on LinkedIn,11%\n11% increase,6%\n-6% decrease,,https://www.linkedin.com/company/holla.world/,30,https://www.linkedin.com/company/holla.world/i...
787,,See all 35 employees on LinkedIn,6%\n6% increase,9%\n9% increase,,http://www.linkedin.com/company/decooda,35,http://www.linkedin.com/company/decooda/insights
788,,See all 53 employees on LinkedIn,4%\n4% increase,2%\n-2% decrease,,https://www.linkedin.com/company/greenbiz-group,53,https://www.linkedin.com/company/greenbiz-grou...
789,,See all 31 employees on LinkedIn,11%\n11% increase,19%\n19% increase,,https://www.linkedin.com/company/bzzagent,31,https://www.linkedin.com/company/bzzagent/insi...
800,37,"See all 1,057 employees on LinkedIn",3%\n3% increase,4%\n4% increase,,http://www.linkedin.com/company/netscribes,1057,http://www.linkedin.com/company/netscribes/ins...
804,1,See all 138 employees on LinkedIn,8%\n8% increase,13%\n13% increase,,https://www.linkedin.com/company/activevideo,138,https://www.linkedin.com/company/activevideo/i...

In [101]:
for i in df_missing.index.to_list():
    driver.get(df_missing['insight_link'][i])
    try:
        element_present = EC.presence_of_all_elements_located((By.CSS_SELECTOR, 'td.org-insights-module__summary-block'))
        WebDriverWait(driver, 7).until(element_present)
        yr_sum = driver.find_elements_by_css_selector('td.org-insights-module__summary-block')
        try:
            df_final['hlfyr'][i]=yr_sum[1].text
        except:
            df_final['hlfyr'][i]=''
        try:  
            df_final['oneyr'][i]=yr_sum[2].text
        except:
            df_final['oneyr'][i]=''
        try:
            df_final['twoyr'][i]=yr_sum[3].text
        except:
            df_final['twoyr'][i]=''
    except:
        
        print('No.'+str(i)+' Insights Page Missing Info')

In [102]:
df_final[(df_final['headcount']>=30)&(df_final['twoyr']=='')]

,job_openings,# employees,hlfyr,oneyr,twoyr,link,headcount
47,19,See all 78 employees on LinkedIn,50%\n50% increase,333%\n333% increase,,https://www.linkedin.com/company/hiextend/,78
157,,See all 40 employees on LinkedIn,18%\n18% increase,90%\n90% increase,,https://www.linkedin.com/company/higg-co,40
411,24,See all 68 employees on LinkedIn,48%\n48% increase,224%\n224% increase,,https://www.linkedin.com/company/aresnalbio/,68
587,3,See all 38 employees on LinkedIn,19%\n19% increase,58%\n58% increase,,https://www.linkedin.com/company/recount-media,38

,job_openings,# employees,hlfyr,oneyr,twoyr,link,headcount
0,7,See all 90 employees on LinkedIn,17%\n17% increase,105%\n105% increase,429%\n429% increase,https://www.linkedin.com/company/finix-payments/,90
1,,See all 89 employees on LinkedIn,1%\n1% increase,3%\n-3% decrease,10%\n10% increase,http://www.linkedin.com/company/4997584,89
2,,See all 26 employees on LinkedIn,,,,https://www.linkedin.com/company/beauty-bakeri...,26
3,15,See all 49 employees on LinkedIn,20%\n20% increase,29%\n29% increase,58%\n58% increase,https://www.linkedin.com/company/goldbelly/,49
4,3,See all 107 employees on LinkedIn,5%\n5% increase,9%\n9% increase,2%\n-2% decrease,https://www.linkedin.com/company/tophatter-com,107
...,...,...,...,...,...,...,...
816,,,,,,https://www.linkedin.com/company/skytide-inc,0
817,,See all 11 employees on LinkedIn,,,,https://www.linkedin.com/company/accordent-tec...,11
818,,,,,,https://www.linkedin.com/company/white-label-m...,0
819,,,,,,http://www.linkedin.com/company/gizmorati,0
820,na,na,na,na,na,https://www.linkedin.com/in/thibaultvignes,0

In [120]:
df_new = pd.read_csv('agg.csv',index_col=0)
df_new

,name,LinkedIn,industry
0,Finix,https://www.linkedin.com/company/finix-payments/,e-commerce
1,Scentbird,http://www.linkedin.com/company/4997584,e-commerce
2,Beauty Bakerie Cosmetics Brand,https://www.linkedin.com/company/beauty-bakeri...,e-commerce
3,Goldbelly,https://www.linkedin.com/company/goldbelly/,e-commerce
4,Tophatter,https://www.linkedin.com/company/tophatter-com,e-commerce
...,...,...,...
816,Skytide,https://www.linkedin.com/company/skytide-inc,social media
817,Accordent Technologies,https://www.linkedin.com/company/accordent-tec...,social media
818,White Label Marketing,https://www.linkedin.com/company/white-label-m...,social media
819,Gizmorati,http://www.linkedin.com/company/gizmorati,social media
820,i2we,https://www.linkedin.com/in/thibaultvignes,social media

In [158]:
df_new['job_openings']=df_final['job_openings']
df_new['# employees'] = df_final['# employees']
df_new['headcount'] = df_final['headcount']
df_new['hlfyr']=df_final['hlfyr']
df_new['oneyr']=df_final['oneyr']
df_new['twoyr']=df_final['twoyr']
df_new = df_new.drop(columns=['# emplpyees'])

In [159]:
df_missing = df_new[(df_new['# employees']=='na') | (df_new['# employees']=='')]

In [165]:
job_links=[]
for i in df_missing['LinkedIn']:
    i = i.replace('-beta','')
    if i[-1] == '/':
        job_link =i+'jobs'
    else:
        job_link=i+'/jobs'
    job_links.append(job_link)

In [166]:
job_links

['https://www.linkedin.com/company/hi-burrow/jobs',
 'http://www.linkedin.com/company/stitch-labs-inc-/jobs',
 'https://www.linkedin.com/company/full-harvest-technologies/jobs',
 'https://www.linkedin.com/company/10838707/jobs',
 'https://www.linkedin.com/in/luisana-mendoza-de-roccia-790197126/jobs',
 'http://www.linkedin.com/company/boomerangcommerce/jobs',
 'https://in.linkedin.com/company/mystery-tackle-box/jobs',
 'https://www.linkedin.com/in/kgreen/jobs',
 'https://www.linkedin.com/company/512204/?pathWildcard=512204/jobs',
 'https://www.linkedin.com/company/green-rush-group/jobs',
 'https://www.linkedin.com/company/project-slice/jobs',
 'http://www.linkedin.com/company/discover-dandelion/jobs',
 'https://www.linkedin.com/company/cover-inc-/jobs',
 'http://www.linkedin.com/company/2693133/jobs',
 'https://www.linkedin.com/in/ccilu-thailand-4671a817a/jobs',
 'https://www.linkedin.com/company/1948217/jobs',
 'https://www.linkedin.com/company/578350/jobs',
 'https://www.linkedin.com/company/glyde-corporation/about/jobs',
 'https://www.linkedin.com/company/weddington-way/jobs',
 'http://www.linkedin.com/company/slimtrader/jobs',
 'https://www.linkedin.com/in/customprintbox/jobs',
 'http://www.linkedin.com/company/luvocracy/jobs',
 'http://www.linkedin.com/company/classic-specs/jobs',
 'https://www.linkedin.com/company/1312462/?pathWildcard=1312462/jobs',
 'http://www.linkedin.com/company/struq/jobs',
 'http://www.linkedin.com/company/datapop/jobs',
 'https://www.linkedin.com/company/itsacheckmate.com-inc./jobs',
 'https://www.linkedin.com/company/diapers.com/jobs',
 'http://www.linkedin.com/company/zingaya/jobs',
 'https://www.linkedin.com/company/dna-response-inc-/jobs',
 'https://www.linkedin.com/company/210924/jobs',
 'http://www.linkedin.com/company/2384467/jobs',
 'http://www.linkedin.com/company/visible-brands-inc./jobs',
 'https://www.linkedin.com/company/1778560/?pathWildcard=1778560/jobs',
 'https://www.linkedin.com/company/truaxis-inc/jobs',
 'https://www.linkedin.com/company/areun-inc-/jobs',
 'https://www.linkedin.com/company/edi-health-group/jobs',
 'http://www.linkedin.com/company/moonjee-corporation/jobs',
 'http://www.linkedin.com/company/thegreenoffice-com/jobs',
 'http://www.linkedin.com/company/carsquare/jobs',
 'http://www.linkedin.com/company/rxspeed/jobs',
 'https://www.linkedin.com/company/recomind-io/jobs',
 'https://www.linkedin.com/company/best-mile/jobs',
 'https://www.linkedin.com/company/12902202/?pathWildcard=12902202/jobs',
 'http://www.linkedin.com/company/veniam-lda/jobs',
 'https://www.linkedin.com/company/15762941/?pathWildcard=15762941/jobs',
 'https://www.linkedin.com/company/withkoji/about/jobs',
 'https://www.linkedin.com/company/best-mile/jobs',
 'https://www.linkedin.com/company/nuvolo-technologies/jobs',
 'https://www.linkedin.com/company/zededa/jobs',
 'https://www.linkedin.com/company/3827017/jobs',
 'https://www.linkedin.com/company/1929799/jobs',
 'https://www.linkedin.com/company/nervanasys/jobs',
 'https://www.linkedin.com/company/6672234?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A6672234%2Cidx%3A2-3-4%2CtarId%3A1449771389351%2Ctas%3Apixva/jobs',
 'http://www.linkedin.com/company/blue-box-group/jobs',
 'https://www.linkedin.com/company/velostrata/jobs',
 'http://www.linkedin.com/company/appfog/jobs',
 'https://www.linkedin.com/company/adar-it/jobs',
 'https://www.linkedin.com/in/bcorcoranthingtech/jobs',
 'http://www.linkedin.com/company/istreamplanet-co./jobs',
 'http://www.linkedin.com/company/accelops-inc./jobs',
 'http://www.linkedin.com/company/elasticbox/jobs',
 'https://www.linkedin.com/company/bubblewrapp-inc-/jobs',
 'http://www.linkedin.com/company/metacloud/jobs',
 'https://www.linkedin.com/company/18121901/jobs',
 'https://www.linkedin.com/company/navera1/jobs',
 'https://www.linkedin.com/company/rollapp/about/jobs',
 'http://www.linkedin.com/company/nscaled-inc./jobs',
 'http://www.linkedin.com/company/3254011/jobs',
 'http://www.linkedin.com/company/solinea/jobs',
 'http://www.linkedin.com/company/orchestrate-io/jobs',
 'http://www.linkedin.com/company/porticor-cloud-security/jobs',
 'http://www.linkedin.com/company/visualops/jobs',
 'http://www.linkedin.com/company/cloud-strategies-llc/jobs',
 'https://in.linkedin.com/company/hive-io/jobs',
 'http://www.linkedin.com/groups/Mobile-Application-Lifecycle-Management-Professionals-4069503?gid=4069503&trk=group-name/jobs',
 'http://www.linkedin.com/company/cloud-weaver/jobs',
 'http://www.linkedin.com/company/stackdriver/jobs',
 'https://www.linkedin.com/in/jtauber/jobs',
 'http://www.linkedin.com/company/magnet-360/jobs',
 'https://www.linkedin.com/company/shunra/about/jobs',
 'https://www.linkedin.com/company/245173/?pathWildcard=245173/jobs',
 'https://www.linkedin.com/company/makara/about/jobs',
 'https://www.linkedin.com/company/blavity/jobs',
 'https://www.linkedin.com/company/commonnetworks/jobs',
 'http://www.linkedin.com/company/identified/jobs',
 'https://www.linkedin.com/company/grokkerinc/jobs',
 'https://www.linkedin.com/company/6672234?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A6672234%2Cidx%3A2-3-4%2CtarId%3A1449771389351%2Ctas%3Apixva/jobs',
 'https://www.linkedin.com/company/17998560/?pathWildcard=17998560/jobs',
 'http://www.linkedin.com/company/shift.com/jobs',
 'https://www.linkedin.com/company/boxmedia_io/jobs',
 'https://www.linkedin.com/company/denimsocial/about/jobs',
 'https://www.linkedin.com/company/dear-media/about/jobs',
 'http://www.linkedin.com/company/istreamplanet-co./jobs',
 'https://www.linkedin.com/company/wait-what-/about/jobs',
 'https://www.linkedin.com/company/upload-vr/jobs',
 'http://www.linkedin.com/company/volometrix/jobs',
 'https://www.linkedin.com/company/578350/jobs',
 'https://www.linkedin.com/company/rankde/jobs',
 'https://www.linkedin.com/company/12902811/jobs',
 'https://www.linkedin.com/company/5004253/jobs',
 'http://www.linkedin.com/company/votigo-inc./jobs',
 'http://www.linkedin.com/company/closely-inc./jobs',
 'http://www.linkedin.com/company/merchant-atlas/jobs',
 'https://www.linkedin.com/company/entangled-media-corp./jobs',
 'https://www.linkedin.com/company/gymgroups/jobs',
 'https://www.linkedin.com/in/phinge-corporation-3b90a116b/jobs',
 'https://www.linkedin.com/company/11016654/?pathWildcard=11016654/jobs',
 'https://www.linkedin.com/company/11074329/jobs',
 'http://www.linkedin.com/company/knowledgevision-systems-incorpor/jobs',
 'http://www.linkedin.com/company/2234089/jobs',
 'https://www.linkedin.com/company/2282155/jobs',
 'https://www.linkedin.com/company/tasty-labs/jobs',
 'http://www.linkedin.com/company/socialkaty-llc/jobs',
 'https://www.linkedin.com/company/28296/jobs',
 'https://www.linkedin.com/company/17961284/jobs',
 'http://www.linkedin.com/company/legolas-media/jobs',
 'http://www.linkedin.com/company/socialvolt/jobs',
 'https://www.linkedin.com/in/mfergason/jobs',
 'https://www.linkedin.com/company/goodreads.com/jobs',
 'http://www.linkedin.com/company/thewrap.com/jobs',
 'https://www.linkedin.com/company/respectance/jobs',
 'http://www.linkedin.com/company/klickthru/jobs',
 'https://www.linkedin.com/company/2751012/jobs',
 'https://www.linkedin.com/company/skytide-inc/jobs',
 'https://www.linkedin.com/company/white-label-marketing/jobs',
 'http://www.linkedin.com/company/gizmorati/jobs',
 'https://www.linkedin.com/in/thibaultvignes/jobs']

In [167]:
df_missing['job_link'] = job_links
df_missing

,name,LinkedIn,industry,job_openings,headcount,hlfyr,oneyr,twoyr,# employees,ppl_link,job_link
21,Burrow,https://www.linkedin.com/company/hi-burrow/,e-commerce,na,0,na,na,na,na,https://www.linkedin.com/company/hi-burrow/people,https://www.linkedin.com/company/hi-burrow/jobs
26,Stitch Labs,http://www.linkedin.com/company/stitch-labs-inc-,e-commerce,na,0,na,na,na,na,http://www.linkedin.com/company/stitch-labs-in...,http://www.linkedin.com/company/stitch-labs-in...
44,Full Harvest,https://www.linkedin.com/company/full-harvest-...,e-commerce,na,0,na,na,na,na,https://www.linkedin.com/company/full-harvest-...,https://www.linkedin.com/company/full-harvest-...
63,AdQuick,https://www.linkedin.com/company-beta/10838707/,e-commerce,na,0,na,na,na,na,https://www.linkedin.com/company/10838707/people,https://www.linkedin.com/company/10838707/jobs
72,Maisonette,https://www.linkedin.com/in/luisana-mendoza-de...,e-commerce,na,0,na,na,na,na,https://www.linkedin.com/in/luisana-mendoza-de...,https://www.linkedin.com/in/luisana-mendoza-de...
...,...,...,...,...,...,...,...,...,...,...,...
809,P3 Global Management,https://www.linkedin.com/company-beta/2751012/,social media,na,0,na,na,na,na,https://www.linkedin.com/company/2751012/people,https://www.linkedin.com/company/2751012/jobs
816,Skytide,https://www.linkedin.com/company/skytide-inc,social media,,0,,,,,https://www.linkedin.com/company/skytide-inc/p...,https://www.linkedin.com/company/skytide-inc/jobs
818,White Label Marketing,https://www.linkedin.com/company/white-label-m...,social media,,0,,,,,https://www.linkedin.com/company/white-label-m...,https://www.linkedin.com/company/white-label-m...
819,Gizmorati,http://www.linkedin.com/company/gizmorati,social media,,0,,,,,http://www.linkedin.com/company/gizmorati/people,http://www.linkedin.com/company/gizmorati/jobs
820,i2we,https://www.linkedin.com/in/thibaultvignes,social media,na,0,na,na,na,na,https://www.linkedin.com/in/thibaultvignes/people,https://www.linkedin.com/in/thibaultvignes/jobs

In [168]:
for i in df_missing.index.to_list():
    try:
        driver.get(df_missing['job_link'][i])
        element_click = EC.element_to_be_clickable((By.LINK_TEXT, 'Insights'))
        WebDriverWait(driver, 5).until(element_click)
        menu = driver.find_element_by_class_name('org-grid__left-rail')
        try:
            df_new['# employees'][i] = driver.find_element_by_partial_link_text('See all').text
        except:
            df_new['# employees'][i] =''

        try:
            element_present = EC.presence_of_element_located((By.CLASS_NAME, 'org-jobs-job-search-form-module__headline'))
            WebDriverWait(driver, 5).until(element_present)
            df_new['job_openings'][i] = int(driver.find_element_by_class_name('org-jobs-job-search-form-module__headline').text.split('job')[0].strip().split(' ')[-1])
        except:
            df_new['job_openings'][i] = ''

        try:
            menu.find_element_by_link_text('Insights').click()
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        except:
            print('No.'+str(i)+' Insights Page Not Clickable')
        #sleep(random.random()*10+3)
        try:
            element_present = EC.presence_of_all_elements_located((By.CSS_SELECTOR, 'td.org-insights-module__summary-block'))
            WebDriverWait(driver, 5).until(element_present)
            yr_sum = driver.find_elements_by_css_selector('td.org-insights-module__summary-block')
            try:
                df_new['hlfyr'][i]=yr_sum[1].text
            except:
                df_new['hlfyr'][i] = ''
            try:
                df_new['oneyr'][i]=yr_sum[2].text
            except:
                df_new['oneyr'][i] = ''
            try:
                df_new['twoyr'][i]=yr_sum[3].text
            except:
                df_new['twoyr'][i] =''
        except:
            print('No.'+str(i)+' Insights Page Missing Info')
        print('No.'+str(i)+' Finished')
    except:
        print('No.'+str(i)+' Link invalid')

No.21 Finished
No.26 Link invalid
No.44 Link invalid
No.63 Finished
No.72 Link invalid
No.98 Link invalid
No.122 Link invalid
No.152 Link invalid
No.162 Insights Page Missing Info
No.162 Finished
No.176 Link invalid
No.177 Link invalid
No.196 Link invalid
No.203 Insights Page Missing Info
No.203 Finished
No.216 Link invalid
No.223 Link invalid
No.224 Insights Page Missing Info
No.224 Finished
No.236 Insights Page Missing Info
No.236 Finished
No.237 Link invalid
No.243 Link invalid
No.246 Insights Page Missing Info
No.246 Finished
No.251 Link invalid
No.252 Insights Page Missing Info
No.252 Finished
No.258 Insights Page Missing Info
No.258 Finished
No.261 Insights Page Missing Info
No.261 Finished
No.263 Link invalid
No.265 Insights Page Missing Info
No.265 Finished
No.279 Link invalid
No.280 Link invalid
No.281 Link invalid
No.282 Link invalid
No.288 Insights Page Missing Info
No.288 Finished
No.289 Link invalid
No.290 Link invalid
No.296 Link invalid
No.306 Insights Page Missing Info
No.306 Finished
No.308 Insights Page Missing Info
No.308 Finished
No.311 Link invalid
No.315 Insights Page Missing Info
No.315 Finished
No.323 Insights Page Missing Info
No.323 Finished
No.325 Link invalid
No.328 Insights Page Missing Info
No.328 Finished
No.332 Insights Page Missing Info
No.332 Finished
No.344 Link invalid
No.346 Insights Page Missing Info
No.346 Finished
No.362 Link invalid
No.365 Insights Page Missing Info
No.365 Finished
No.390 Link invalid
No.391 Link invalid
No.402 Link invalid
No.403 Link invalid
No.417 Insights Page Missing Info
No.417 Finished
No.431 Insights Page Missing Info
No.431 Finished
No.437 Insights Page Missing Info
No.437 Finished
No.441 Link invalid
No.447 Link invalid
No.449 Link invalid
No.455 Link invalid
No.457 Link invalid
No.464 Link invalid
No.473 Link invalid
No.476 Link invalid
No.478 Link invalid
No.481 Link invalid
No.483 Link invalid
No.487 Insights Page Missing Info
No.487 Finished
No.490 Link invalid
No.502 Link invalid
No.504 Link invalid
No.506 Insights Page Missing Info
No.506 Finished
No.510 Link invalid
No.512 Link invalid
No.513 Insights Page Missing Info
No.513 Finished
No.519 Insights Page Missing Info
No.519 Finished
No.520 Insights Page Missing Info
No.520 Finished
No.522 Link invalid
No.523 Link invalid
No.524 Insights Page Missing Info
No.524 Finished
No.526 Insights Page Missing Info
No.526 Finished
No.527 Link invalid
No.528 Link invalid
No.529 Link invalid
No.535 Link invalid
No.536 Link invalid
No.539 Link invalid
No.558 Link invalid
No.560 Link invalid
No.590 Link invalid
No.619 Link invalid
No.625 Insights Page Missing Info
No.625 Finished
No.652 Link invalid
No.670 Link invalid
No.673 Link invalid
No.675 Link invalid
No.679 Link invalid
No.683 Link invalid
No.684 Link invalid
No.688 Insights Page Missing Info
No.688 Finished
No.700 Insights Page Missing Info
No.700 Finished
No.703 Link invalid
No.712 Insights Page Missing Info
No.712 Finished
No.727 Insights Page Missing Info
No.727 Finished
No.728 Link invalid
No.732 Link invalid
No.739 Insights Page Missing Info
No.739 Finished
No.741 Insights Page Missing Info
No.741 Finished
No.742 Link invalid
No.746 Link invalid
No.747 Insights Page Missing Info
No.747 Finished
No.751 Insights Page Missing Info
No.751 Finished
No.758 Link invalid
No.759 Link invalid
No.767 Insights Page Missing Info
No.767 Finished
No.773 Link invalid
No.778 Link invalid
No.780 Insights Page Missing Info
No.780 Finished
No.781 Link invalid
No.782 Link invalid
No.790 Link invalid
No.791 Link invalid
No.801 Link invalid
No.802 Link invalid
No.806 Insights Page Missing Info
No.806 Finished
No.808 Insights Page Missing Info
No.808 Finished
No.809 Insights Page Missing Info
No.809 Finished
No.816 Insights Page Missing Info
No.816 Finished
No.818 Insights Page Missing Info
No.818 Finished
No.819 Insights Page Missing Info
No.819 Finished
No.820 Link invalid

In [184]:
number_lst = []
for i in df_final['# employees']:
    try:
        number = int(i.split(' ')[2].replace(',',''))
    except:
        number = 0
    number_lst.append(number)
df_final['headcount']=number_lst

In [186]:
df_new[(df_new['# employees']=='na') | (df_new['# employees']=='')]
df_new[(df_new['headcount']>=30) &(df_new['twoyr']=='')]

,name,LinkedIn,industry,job_openings,headcount,hlfyr,oneyr,twoyr,# employees
47,Extend,https://www.linkedin.com/company/hiextend/,e-commerce,19,78,50%\n50% increase,333%\n333% increase,,See all 78 employees on LinkedIn
157,Higg Co,https://www.linkedin.com/company/higg-co,e-commerce,,40,18%\n18% increase,90%\n90% increase,,See all 40 employees on LinkedIn
411,ArsenalBio,https://www.linkedin.com/company/aresnalbio/,cloud,24,68,48%\n48% increase,224%\n224% increase,,See all 68 employees on LinkedIn
587,Recount Media,https://www.linkedin.com/company/recount-media,social media,3,38,19%\n19% increase,58%\n58% increase,,See all 38 employees on LinkedIn

In [187]:
df_new.to_csv('LinkedIn_2.csv',index=False)

In [327]:
def find_link(i):
    try:
        elem = driver.find_element_by_xpath("/html/body/div[7]/div[3]/div/div[3]/div[2]/div[2]/div[2]/ul/li"+'['+str(i+1)+']/div/section/div/div/div[1]/a')
        link = elem.get_attribute('href')
        return link
    except:
        pass

In [251]:
def scroll_to_bottom(driver):

    old_position = 0
    new_position = None

    while new_position != old_position:
        # Get old scroll position
        old_position = driver.execute_script(
                ("return (window.pageYOffset !== undefined) ?"
                 " window.pageYOffset : (document.documentElement ||"
                 " document.body.parentNode || document.body);"))
        # Sleep and Scroll
        time.sleep(1)
        driver.execute_script((
                "var scrollingElement = (document.scrollingElement ||"
                " document.body);scrollingElement.scrollTop ="
                " scrollingElement.scrollHeight;"))
        # Get new position
        new_position = driver.execute_script(
                ("return (window.pageYOffset !== undefined) ?"
                 " window.pageYOffset : (document.documentElement ||"
                 " document.body.parentNode || document.body);"))